language: node_js
node_js:
- iojs-v1
- '0.12'
- '0.10'
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: dti/mr7g8Z7H0dvrelhVtshiq7eeebl5R3iD1X+fK0GbUR5M0xBivuM0+69vD1WyTrD1B1uYD+WEAa+KMyDvItG+sXO+q0fPlsP3OqNTcPtBKOSq2BdM7XyuE3/q8T5xn9e3kcAvlmpYvUYWEUI7/A90bjz59uIBjMxdhFRKvxM=
before_install:
- npm i -g npm@^2.0.0
- npm prune
before_script:
- curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
after_success:
- python travis_after_all.py
- export $(cat .to_export_back)
after_failure:
- python travis_after_all.py
- export $(cat .to_export_back)
before_deploy:
- rm -f travis_after_all.py .to_export_back
after_script:
- echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
deploy:
  provider: npm
  email: david@excellenteasy.com
  skip_cleanup: true
  on:
    branch: master
    repo: excellenteasy/ios-splash
  api_key:
    secure: SFyySY6zqwpJLXE5ycEC++6a4kWNqOiYxEjazRoFVT6aIxDld1YBO3FirJUzxg8gMNWsK3sQCowqBIYx5hQZjm4lx1NIOTeT0flXULUNNM4teuthoNp+vauQV7SqIo92xy9DoqJc6usSvsj/uzNNJSxi5Wn1LgMd/H5BA0/1XYY=
env: global:GH_TOKEN=c4d321258c51f4efb309a89ac52a05bd49b63a51
